### ISSUE TITLE
gold_answers NOT found

### ISSUE THREAD

**Issue by ElonSteveMask** [adobe-research/NoLiMa#1]
At this moment, the latest commit is `1a1cd401acdab5108a4795486dd0083272e014ec`

Following the instructions in README.md, the evaluations are performed using `evaluation/run_test.sh` as follows
```bash
export PYTHONPATH="../"
echo $$
python -u run_tests.py --config run_config/multi_test_config_book_250.yaml
python -u run_tests.py --config run_config/multi_test_config_book_500.yaml
python -u run_tests.py --config run_config/multi_test_config_book_1K.yaml
python -u run_tests.py --config run_config/multi_test_config_book_2K.yaml
python -u run_tests.py --config run_config/multi_test_config_book_4K.yaml
python -u run_tests.py --config run_config/multi_test_config_book_8K.yaml
python -u run_tests.py --config run_config/multi_test_config_book_16K.yaml
python -u run_tests.py --config run_config/multi_test_config_book_32K.yaml
```

Take `run_config/multi_test_config_book_1K.yaml` for example,
```yaml
model_name: "gpt_4o_20241120"
model_configs_dir: "./model_configs/"
needle_set_path: "../data/needlesets/needle_set.json"
haystack_dir: "../data/haystack/rand_shuffle"
parent_results_dir: "./results_gpt_4o_20241120/CL1K/"
context_length: 1000
document_depth_percent_min: 0
document_depth_percent_max: 100
document_depth_percent_intervals: 26
metric: contains
use_default_system_prompt: true
```
the `needle_set_path` points to `"../data/needlesets/needle_set.json"`, which can be downloaded from the link `https://huggingface.co/datasets/amodaresi/NoLiMa/resolve/main/needlesets/needle_set.json`. However, there is no `gold_answers` inside. While the `_evaluate_response` [function](https://github.com/adobe-research/NoLiMa/blob/1a1cd401acdab5108a4795486dd0083272e014ec/evaluation/async_evaluate.py#L114) depends on the `gold_answers` field. So where to get the `gold_answers` field or infer it manually?
